### PR TITLE
fixed variable.function.php color

### PR DESCRIPTION
**Pull request by ajayexpert**
Fixed variable.function.php color

In php method chaining unable to to identify which one is method or which one is variable so fixed color on method.

Before Fix

screenshot from 2018-09-03 04-24-06

After Fix

screenshot from 2018-09-03 04-24-28

### CODE REVIEW

**Comment by gerardroche** [comment]
Hmm. The reason user defined functions and methods are not blue is because builtin functions are blue.

screenshot from 2018-09-03 00-54-16

**Comment by ajayexpert** [comment]
Now built-in function will highlight in `italic` 

screenshot from 2018-09-03 06-10-29

**Comment by gerardroche** [comment]
I don't know yet. I'm going to try it for a bit and see how it feels.

**Comment by gerardroche** [comment]
It's a lot of blue!

screenshot from 2018-09-03 03-07-00

**Comment by ajayexpert** [comment]
Actually i used to this color combination. i feel uncomfortable with other color combination. i have tried very hard to find this combination.

**Comment by gerardroche** [comment]
I can't get used to all the blue. This is probably not going to get merged. What I will suggest is using a color scheme override instead of forking, because it allows you to just tweak the things you want and still get updates from the base color scheme. 

Create a file name **MonokaiFree.sublime-color-scheme** in the Sublime Text **User** directory (**Menu > Preferences > Browse Packages...**), and add this:

```
{
    "rules":
    [
        {
            "scope": "variable.function.php",
            "foreground": "#66d9ef"
        },
        {
            "scope": "support.function",
            "foreground": "#66d9ef",
            "font_style": "italic"
        }
    ]
}
```

The rules will override the rules in MonokaiFree (essentially merge the rules on top of MonokaiFree).
See also: https://github.com/gerardroche/sublime-monokai-free#customisation.

**Comment by ajayexpert** [comment]
Got the solution by @gerardroche.

**Pull request closed without merging**
